# https://docs.docker.com/go/compose-spec-reference/
# TODO
services:
  server:
    container_name: ministore
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PW=${POSTGRES_PW}
    networks:
      - spring-ministore
    volumes:
      - uploads-data:/uploads
    # develop:
    # watch:
    # - path: .
    # action: rebuild
  db:
    container_name: postgres-db
    image: postgres:latest
    # restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - spring-ministore
volumes:
  db-data:
  uploads-data:
networks:
  spring-ministore:
